In [2]:
import numpy as np

In [5]:
b=np.arange(1,100,5)
b

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [8]:
b=np.arange(1,100,5).reshape(4,5)
b

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [10]:
# sicing a matrix
b[0:2,1:4]

array([[ 6, 11, 16],
       [31, 36, 41]])

In [11]:
b.max()

96

In [12]:
b.sum()

970

In [13]:
b.min(axis=0)

array([ 1,  6, 11, 16, 21])

In [16]:
c=((5,2),(5,4),(7,8))
c

((5, 2), (5, 4), (7, 8))

In [21]:
d=np.arange(1,12,2).reshape(3,2)
d

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [22]:
c*d

array([[ 5,  6],
       [25, 28],
       [63, 88]])

In [23]:
c+d

array([[ 6,  5],
       [10, 11],
       [16, 19]])

In [24]:
np.flip(c)

array([[8, 7],
       [4, 5],
       [2, 5]])