In [1]:
print(2+3)


5


In [2]:
print("Hello World")


Hello World


In [3]:
print("We are learning Python with Adeel")


We are learning Python with Adeel


# Operations in python

In [4]:
print(2+1)


3


In [5]:
print(4-5)


-1


In [6]:
print(5*3)


15


In [7]:
print(4/2)


2.0


In [8]:
print(17%3) #(Remainder)


2


In [9]:
print(7//2) #(No floating value)


3


In [10]:
print(3**4) #(Power function)


81


In [11]:
print(3**2/2*4/3+5-3) # PEMDAS

8.0


In [12]:
a= "Hello World" 
a

'Hello World'

In [2]:
#Arithematic Operation in Python
a=11;b=3
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a//b) # No floating function

14
8
33
3.6666666666666665
2
1331
3


In [3]:
#Comparision Operation in Python
a=11;b=11
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(a!=b)
print(a==b)

False
False
True
True
False
True


In [10]:
#Assignment Operators (=, +=, -=, *= .....)
a=2
print(a)
a*=2; # a= a*2
print(a)

2
4


In [13]:
b = "We are learning Python with Adeel" 
b

'We are learning Python with Adeel'

In [14]:
c= 20 #int

In [15]:
d = 20.5 #float
d

20.5

# Data Types in Python
Text: str #String\
Numeric: int, float\
Sequence: list, tuple, range\
Mapping: dictionary\
Set: set\
Boolean: bool #True/ False

## String

In [7]:
string="My name is {Adeel} and i am from {Lahore}"
print(string)   


My name is {Adeel} and i am from {Lahore}


In [11]:
string="My name is {0} and i am from {1}"
Name="Adeel"
City="Lahore"
print(string.format(Name,City))

My name is Adeel and i am from Lahore


In [14]:
string=(f"My name is {Name} and i am from {City}")
print(string)

My name is Adeel and i am from Lahore


In [17]:
price=50.5235656
print("The price of the product is {price:.2f}")

The price of the product is {price:.2f}


In [18]:
price=50.5235656
print(f"The price of the product is {price:.2f}")

The price of the product is 50.52


In [16]:
e = ["apple","banana","orange",20.5,True,15] #list
e

['apple', 'banana', 'orange', 20.5, True, 15]

In [17]:
f = ("apple","banana","orange",20.5,True,15) #tuple
f

('apple', 'banana', 'orange', 20.5, True, 15)

In [18]:
g = {"name":"Abdul Hannan","age":27,"weight":76.5,"height":167.5} #dict
g

{'name': 'Abdul Hannan', 'age': 27, 'weight': 76.5, 'height': 167.5}

In [19]:
a="Pakistan"
print(a[0])
print(a[4])
print(a[0:5])

P
s
Pakis


In [20]:
x="zeshan"
print(x)
print(x.upper())
print(x.replace("a","e"))

zeshan
ZESHAN
zeshen


In [21]:
print(a[:7])
print(a[1:])
print(a[-4:]) 
print(a[:-3])                        

Pakista
akistan
stan
Pakis


# Lists[]

Ordered collection of elements\
Enclosed in [] brackets\
Mutable\
Lists allow duplicate elements, and the order in which elements are added is preserved.

In [2]:
list1=[2,5,63,25,21,33,65,9,89,8,25]
list1

[2, 5, 63, 25, 21, 33, 65, 9, 89, 8, 25]

In [3]:
list1.sort()
list1

[2, 5, 8, 9, 21, 25, 25, 33, 63, 65, 89]

In [4]:
list1.sort(reverse=True)
list1

[89, 65, 63, 33, 25, 25, 21, 9, 8, 5, 2]

In [5]:
print(list1.count(25))

2


In [24]:
len(list1)

11

In [25]:
list1*3

[2,
 5,
 8,
 9,
 21,
 25,
 25,
 33,
 63,
 65,
 89,
 2,
 5,
 8,
 9,
 21,
 25,
 25,
 33,
 63,
 65,
 89,
 2,
 5,
 8,
 9,
 21,
 25,
 25,
 33,
 63,
 65,
 89]

In [26]:
list1.append("B")
list1


[2, 5, 8, 9, 21, 25, 25, 33, 63, 65, 89, 'B']

In [27]:
# To add the B in the middle of list
list1.insert(5,"B")
list1

[2, 5, 8, 9, 21, 'B', 25, 25, 33, 63, 65, 89, 'B']

In [28]:
# To remove the B from middle of the list
list1.remove("B")
list1

[2, 5, 8, 9, 21, 25, 25, 33, 63, 65, 89, 'B']

In [29]:
myList = ['abc', 'def', 'ghij']
myList.append('klm')
myList

['abc', 'def', 'ghij', 'klm']

In [30]:
myList2 = [1,2,3]
myList3 = [4,5,6]
myList2 + myList3

[1, 2, 3, 4, 5, 6]

# Dictionaries{}
Unordered collection of elements\
Key and Value\
enclosed in {} brackets\
Mutable


In [5]:
dic1={"a":25,"b":65,"c":98,"d":87}
dic1

{'a': 25, 'b': 65, 'c': 98, 'd': 87}

In [6]:
dic1.pop("a") # To remove the key from dictionary, pop 


25

In [7]:
dic1

{'b': 65, 'c': 98, 'd': 87}

In [8]:
dic1.values()

dict_values([65, 98, 87])

In [9]:
dic1.keys()

dict_keys(['b', 'c', 'd'])

In [10]:
dic1["e"]=10
print(dic1)
dict_2 = {"f": 120, "g":110,"h":70}
print(dict_2)
dict_2.update(dic1)
print(dict_2)


{'b': 65, 'c': 98, 'd': 87, 'e': 10}
{'f': 120, 'g': 110, 'h': 70}
{'f': 120, 'g': 110, 'h': 70, 'b': 65, 'c': 98, 'd': 87, 'e': 10}


In [12]:
# example of dictionary with students names and marks
marks = {"Ali": 50, "Ahmed": 70, "Hassan": 90, "Khalid": 80, "Nasir": 60}
marks

{'Ali': 50, 'Ahmed': 70, 'Hassan': 90, 'Khalid': 80, 'Nasir': 60}

In [11]:
# Example of nested dictionary
nested_dict = {"first":{"a":1},"second":{"b":2}}, {"third":{"c":3}}, {"fourth":{"d":4}}, {"fifth":{"e":5}}
print(nested_dict)

({'first': {'a': 1}, 'second': {'b': 2}}, {'third': {'c': 3}}, {'fourth': {'d': 4}}, {'fifth': {'e': 5}})


# Tuple()
Tuples are ordered, maintaining the order of elements.\
Enclosed in () braces\
Different kind of elements can be stored\
Immutable\
Allow Duplicates


In [35]:
tup_1=(2,"Pak",True,4.3)
tup_1

(2, 'Pak', True, 4.3)

In [36]:
tup_2=(4,"Pakistan",False,3.6)
tup_2

(4, 'Pakistan', False, 3.6)

In [37]:
tup_1+tup_2

(2, 'Pak', True, 4.3, 4, 'Pakistan', False, 3.6)

In [38]:
tup_1*2+tup_2

(2, 'Pak', True, 4.3, 2, 'Pak', True, 4.3, 4, 'Pakistan', False, 3.6)

In [39]:
tup_3=(40,33,45,76,87,98,34,65,89)
tup_3

(40, 33, 45, 76, 87, 98, 34, 65, 89)

In [40]:
print(max(tup_3))
print(min(tup_3))


98
33


In [41]:
import numpy as np
myTuple = ('abc', np.arange(0,3,0.2), 2.5)
myTuple[2]


2.5

# Sets()
Sets are mutable, meaning you can add or remove elements after the set is created.\
Unordered and Unindexed:Sets are unordered, meaning they do not maintain any specific order of elements.\
No Duplicates Allowed\
enclosed in () brackets



In [42]:
s1={1,2,5,"karachi", "lahore", "islamabad"}
print(s1)
s1.add("patoki")
print(s1)


{1, 2, 5, 'islamabad', 'lahore', 'karachi'}
{1, 2, 5, 'islamabad', 'patoki', 'lahore', 'karachi'}


In [37]:
cities1={"karachi","lahore","islamabad","patoki"}
cities2={"lahore","multan","hyderabad","naran"}

In [38]:
cities1.union(cities2)

{'hyderabad', 'islamabad', 'karachi', 'lahore', 'multan', 'naran', 'patoki'}

In [39]:
cities1.intersection(cities2)

{'lahore'}

# Array
An array is a data structure that stores a collection of elements, typically of the same type, in connecting memory locations.
 
Arrays are fundamental in computer science and programming because they provide efficient ways to organize and access data. Here are some key characteristics and types of arrays.
# Types of Arrays
# One-Dimensional Array
A simple linear array where elements are arranged in a single row or column.
# Two-Dimensional Array
An array of arrays, where elements are arranged in rows and columns, forming a grid-like structure.
# Multi-Dimensional Array
An array with more than two dimensions, extending the concept of two-dimensional arrays to higher dimensions.



In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [44]:
b=np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [45]:
c=np.ones(4)
c

array([1., 1., 1., 1.])

In [46]:
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
e=np.arange(2,10)
e

array([2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
f=np.arange(1,100,5)
f

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

# 2-D array

In [49]:
np.array([[1,2,3,5,6],[5,3,6,2,1]])

array([[1, 2, 3, 5, 6],
       [5, 3, 6, 2, 1]])

In [50]:
print(np.ones((4,5)))
print(np.ones((6,7)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


# 3-D array

In [51]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [52]:
a=np.array([[[1,2,5,6],
[5,7,8,11]],
[[9,5,2,3],
[8,7,4,5]],
[[5,4,3,2],
[5,6,4,2]]])
a

array([[[ 1,  2,  5,  6],
        [ 5,  7,  8, 11]],

       [[ 9,  5,  2,  3],
        [ 8,  7,  4,  5]],

       [[ 5,  4,  3,  2],
        [ 5,  6,  4,  2]]])

In [53]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
print(a.ndim)
print(a.size)
print(a.shape)


3
24
(2, 3, 4)


In [55]:
b=np.arange(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
c=b.reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Matrices

In [57]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import pandas as pd
import seaborn as sns 

In [58]:
b=np.arange(1,100,5)
b

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [59]:
b=np.arange(1,100,5).reshape(4,5)
b

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [60]:
print(b[0:2,1:4])
print(b.max())
print(b.sum())
print(b.min(axis=0))


[[ 6 11 16]
 [31 36 41]]
96
970
[ 1  6 11 16 21]


In [61]:
c=((5,2),(5,4),(7,8))
c

((5, 2), (5, 4), (7, 8))

In [62]:
d=np.arange(1,12,2).reshape(3,2)
d

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [63]:
print(c*d)
print(c+d)


[[ 5  6]
 [25 28]
 [63 88]]
[[ 6  5]
 [10 11]
 [16 19]]


In [64]:
z=np.arange(24).reshape(2,3,4)
z

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Conditional formatting

In [65]:
a=5
b=15
c=20.5

In [66]:
if a<b: 
       print("a is less than b")

a is less than b


In [67]:
if c<b:
    print("c is less than b")
else:
    print("c is greater than b")

c is greater than b


In [68]:
person_a_name=input("Enter your name: ")
person_a_age=input("Enter your age: ")
person_b_name=input("Enter your name: ")
person_b_age=input("Enter your age: ")

In [69]:
if person_a_age > person_b_age:
    print(person_a_name,"is older than", person_b_name)
elif person_a_age < person_b_age:
    print(person_a_name," is younger than",person_b_name)
else:
    print(person_a_name,"is the same age as",person_b_name)

adeel is older than yaseen


# BMI

In [27]:
Height=input("Enter your height in cms: ")
Height
Height=float(Height)

In [28]:
weight=float(input("Enter your weight in kgs: "))
weight

10.0

In [29]:
BMI=weight/Height**2
BMI

0.4

In [14]:
a=input("Enter the number: ")
for i in range (1,100):
    print(a,"x",i,"=",int(a)*i)

100 x 1 = 100
100 x 2 = 200
100 x 3 = 300
100 x 4 = 400
100 x 5 = 500
100 x 6 = 600
100 x 7 = 700
100 x 8 = 800
100 x 9 = 900
100 x 10 = 1000
100 x 11 = 1100
100 x 12 = 1200
100 x 13 = 1300
100 x 14 = 1400
100 x 15 = 1500
100 x 16 = 1600
100 x 17 = 1700
100 x 18 = 1800
100 x 19 = 1900
100 x 20 = 2000
100 x 21 = 2100
100 x 22 = 2200
100 x 23 = 2300
100 x 24 = 2400
100 x 25 = 2500
100 x 26 = 2600
100 x 27 = 2700
100 x 28 = 2800
100 x 29 = 2900
100 x 30 = 3000
100 x 31 = 3100
100 x 32 = 3200
100 x 33 = 3300
100 x 34 = 3400
100 x 35 = 3500
100 x 36 = 3600
100 x 37 = 3700
100 x 38 = 3800
100 x 39 = 3900
100 x 40 = 4000
100 x 41 = 4100
100 x 42 = 4200
100 x 43 = 4300
100 x 44 = 4400
100 x 45 = 4500
100 x 46 = 4600
100 x 47 = 4700
100 x 48 = 4800
100 x 49 = 4900
100 x 50 = 5000
100 x 51 = 5100
100 x 52 = 5200
100 x 53 = 5300
100 x 54 = 5400
100 x 55 = 5500
100 x 56 = 5600
100 x 57 = 5700
100 x 58 = 5800
100 x 59 = 5900
100 x 60 = 6000
100 x 61 = 6100
100 x 62 = 6200
100 x 63 = 6300
100 x 64 =

In [16]:
# Value errors
a=int(input("Enter the number between 1 and 10: "))
if a>10 or a<1:
    raise ValueError("The number is not between 1 and 10")
   


# Loops
Both for and while are control flow statements in programming languages that allow you to create loops, which are used for repeating a block of code multiple times.\
The for loop is typically used when you know in advance how many times you want to iterate, and you have a sequence (list, tuple, string, etc.) to iterate over.\

The while loop is used when you don't know in advance how many times the loop needs to run. It continues iterating as long as the specified condition is True.\

Use a for loop when you know the number of iterations in advance and have a sequence to iterate over. Use a while loop when the number of iterations is not known in advance and is determined by a condition


In [73]:
# For loop
foods=['bacon','tuna','ham','sausages','beef','eggs','chicken']
for food in foods:
	print(food)


bacon
tuna
ham
sausages
beef
eggs
chicken


In [74]:
# write good example of for loop
for x in range(1,11):
    print(x) 

1
2
3
4
5
6
7
8
9
10


In [75]:
for x in range(1,11,2):
    print(x)

1
3
5
7
9


In [76]:
# While loop
i=1
while i<=20:
    print(i)
    i+=2

1
3
5
7
9
11
13
15
17
19


In [77]:
# for loop with if else
for x in range(1,11):
    if x%2==0:
        print(x,"is even")
    else:
        print(x,"is odd")

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
10 is even


In [78]:
# for nested loops
colors=["red","green","blue","yellow","orange","purple"]
items=["shirt","hat","socks","pants","jacket","shorts"]
for color in colors:
    for item in items:
        print(color,item)

red shirt
red hat
red socks
red pants
red jacket
red shorts
green shirt
green hat
green socks
green pants
green jacket
green shorts
blue shirt
blue hat
blue socks
blue pants
blue jacket
blue shorts
yellow shirt
yellow hat
yellow socks
yellow pants
yellow jacket
yellow shorts
orange shirt
orange hat
orange socks
orange pants
orange jacket
orange shorts
purple shirt
purple hat
purple socks
purple pants
purple jacket
purple shorts


In [79]:
for i in range(1,100,30):
    for j in range (200,300,20):
        print(i*j)

200
220
240
260
280
6200
6820
7440
8060
8680
12200
13420
14640
15860
17080
18200
20020
21840
23660
25480


In [80]:
# for loop inside while loop
i = 1
while i < 10:
    for j in range(1,10):
        print(i, j)
    i+=1

1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
5 1
5 2
5 3
5 4
5 5
5 6
5 7
5 8
5 9
6 1
6 2
6 3
6 4
6 5
6 6
6 7
6 8
6 9
7 1
7 2
7 3
7 4
7 5
7 6
7 7
7 8
7 9
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9


In [81]:
# while loop inside for loop
for i in range(1,10):
    j = 1
    while j < 10:
        print(i, j)
        j+=1

1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
5 1
5 2
5 3
5 4
5 5
5 6
5 7
5 8
5 9
6 1
6 2
6 3
6 4
6 5
6 6
6 7
6 8
6 9
7 1
7 2
7 3
7 4
7 5
7 6
7 7
7 8
7 9
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9


In [82]:
i = 0
while i < 5:
    print(i)
    i += 1
    if i == 3:
        break
else:
    print(0)

0
1
2


In [1]:
#continue, break, pass
for i in range(1,11):

  if i==1:
    pass
  if i==5:
    continue
  if i==8:
    break
  print ("This is iteration no. ", i)

This is iteration no.  1
This is iteration no.  2
This is iteration no.  3
This is iteration no.  4
This is iteration no.  6
This is iteration no.  7


# enumerate function

In [19]:
marks=[5,56,71,89,45,67,90,34,78,98]
index=0
for mark in marks:
    if (index==5):
        print("We are learning pythin ")
    print(mark)
    index +=1

5
56
71
89
45
We are learning pythin 
67
90
34
78
98


In [21]:
# but we can do it with enumerate function more easily
marks=[5,56,71,89,45,67,90,34,78,98]
for index, mark in enumerate (marks):
    if (index==5):
        print("We are learning pythin ")
    print(mark)


5
56
71
89
45
We are learning pythin 
67
90
34
78
98


In [22]:
# but we can do it with enumerate function more easily
marks=[5,56,71,89,45,67,90,34,78,98]
for index, mark in enumerate (marks, start=1):
    if (index==5):
        print("We are learning pythin ")
    print(mark)

5
56
71
89
We are learning pythin 
45
67
90
34
78
98


# Functions

# def function
In most programming languages, including Python, the def keyword is used to define a function. A function is a block of reusable code that performs a specific task or a set of tasks. Functions are a fundamental concept in programming as they allow you to organize code into modular and reusable units.


# lambda function
In Python, a lambda function is a concise way to create anonymous (unnamed) functions. Lambda functions are also known as anonymous functions or lambda expressions. They are defined using the lambda keyword and can take any number of parameters.\
It's important to note that while lambda functions are useful for certain situations, they are limited compared to named functions. Lambda functions are best suited for simple operations, and for more complex functionality, it is often more readable and maintainable to use a regular named function.


In [22]:
def square(number):
    return number*number
print(square(5))

25


In [23]:
def add(a,b):
    return a+b
print(add(2,3))

5


In [31]:
# Factorial
print(7*6*5*4*3*2*1)
print(6*5*4*3*2*1)
print(5*4*3*2*1)
# factorial of 0 is 1 by definition
print(4*3*2*1)
# so we can write that
# factorial (n)=n*factorial(n-1)

5040
720
120
24


In [32]:
# Now we can make a function for factorial
def factorial (n):
    if n==0 or n==1:
        return 1
    else:
        return n*factorial(n-1)

In [34]:
factorial(3)

6

In [20]:

# pass a function into a function
def cube (number):
    return number**3
print(cube(5))
# use this function in another function is given below

125


In [21]:

def apply(fx, value):
    return 6+ fx(value)
print (apply(cube, 4))

70


# Lambda function

In [3]:
def double(x):
    return x*2
print(double(5))
print(double(7))

10
14


In [4]:
# We can write this function as
double=lambda x: x*2
print(double(5))

10


In [16]:
cube=lambda x: x**3
print(cube(4))

64


In [85]:
# Lambda function
x = lambda a,b:a+b
print(x(2,3))

5


In [86]:
x=lambda a: a*5
print(x(2))

10


In [87]:
x=lambda a,b,c: a+b+c
print(x(2,3,4))

9


In [88]:
# pip install openpyxl

# Map function

In [ ]:
def cube (x):
    return x**3
# Now we can use this function in map function
l=[1,3,4,5,8,15]
for i in l:
    print(cube(i))

In [4]:
def cube (x):
    return x**3
print(cube(5))
# Now we can use this function in map function
l=[1,3,4,5,8,15]
list=[]
for i in l:
    list.append(cube(i))
    print(list)

125
[1]
[1, 27]
[1, 27, 64]
[1, 27, 64, 125]
[1, 27, 64, 125, 512]
[1, 27, 64, 125, 512, 3375]


In [2]:
def cube (x):
    return x**3
my_list = [1, 3, 4, 5, 8, 15]
new_list = list(map(cube, my_list))
print(new_list)


[1, 27, 64, 125, 512, 3375]


# Filter function

In [6]:
# Filter function
def filter_function (a):
    return a>3
list(filter(filter_function,my_list))


[4, 5, 8, 15]

# Classes and objects

In [16]:
# Class is a blueprint for creating objects. An object has properties and methods(functions) associated with it. Almost everything in Python is an object, with its properties and methods. A Class is like an object constructor, or a "blueprint" for creating objects.

In [6]:
class person:
    name="Adeel"
    Occupation="Lecturer"
    networth="1M PKR"
    

In [11]:
a= person()
a.name="Adeel munir"
a.Occupation="Data Scientist"
print (a.name, a.Occupation)

Adeel munir Data Scientist


In [13]:
class person:
    name="Adeel"
    Occupation="Lecturer"
    networth="1M PKR"
    def info(self):
        return f"{self.name} is a {self.Occupation} and his networth is {self.networth}"

In [15]:
a= person()
a.info()

'Adeel is a Lecturer and his networth is 1M PKR'

In [17]:
a= person()
b= person()
b.name="Ali"
b.Occupation="HR"
b.networth="2M PKR"
b.info()

'Ali is a HR and his networth is 2M PKR'

# Constructor
In summary, constructors make object creation more structured, clear, and error-free. They allow you to set up objects with the necessary initial values and provide consistency across your code

In [1]:
class Car:
    # Constructor method to initialize attributes
    def __init__(self, brand, model, year):
        self.brand = brand  # 'self' refers to the instance of the object
        self.model = model
        self.year = year

    # Method to display car details
    def car_details(self):
        print(f"Car: {self.year} {self.brand} {self.model}")

# Creating an object of Car class
my_car = Car("Toyota", "Corolla", 2021)

# Accessing the car's details
my_car.car_details()



Car: 2021 Toyota Corolla
